version: "3.7"
services:
  test:
    volumes:
      - .:/project
      - ./cache:/env
      - ./tests/firefox/profile:/profile
    image: quay.io/sandorex/ebd-test-image
    build:
      context: ./docker
    entrypoint: [ "/entrypoint.sh" ]
    command: [ "test" ]
