version: "3.7"
services:
  test:
    volumes:
      - .:/project
    image: quay.io/sandorex/ebd-test-image:testing-using-docker
    build:
      context: ./docker
    entrypoint: [ "/entrypoint.sh" ]
