version: "3.7"
services:
  test:
    volumes:
      - .:/project
    image: docker.pkg.github.com/sandorex/extract-browser-data.py/test-image
    build:
      context: ./docker
    entrypoint: [ "/entrypoint.sh" ]
    environment:
      # these are required cause chromium crashes in docker because of namespace
      # issues
      - CHROMIUM_ARGS=--no-sandbox --disable-gpu
