version: "3.7"
services:
  test:
    volumes:
      - .:/project
    image: quay.io/sandorex/ebd-test-image
    build:
      context: ./docker
    entrypoint: [ "/entrypoint.sh" ]
    environment:
      # these are required cause chromium crashes in docker because of namespace
      # issues
      - CHROMIUM_ARGS=--no-sandbox --disable-gpu
