version: "3.7"
services:
  test:
    volumes:
      - .:/project
    image: quay.io/sandorex/ebd-test-image:ci-testing
    build:
      context: ./docker
    entrypoint: [ "/entrypoint.sh" ]

  test-ci:
    volumes:
      - .:/project
    build:
      context: ./docker
      dockerfile: Dockerfile.ci
    entrypoint: [ "/entrypoint.sh" ]
