#!/usr/bin/env bash

set -e

VENV_LOGFILE=/tmp/venv.log
PIP_LOGFILE=/tmp/pip.log
PIP_ARGS=--disable-pip-version-check

# ensure user owns /env
sudo mkdir -p /env
sudo chown -R user:user /env

# setup the trap to print logs on error
function _err() {
   print_logfile "$PIP_LOGFILE" 'Pip log output'
   echo
   print_logfile "$VENV_LOGFILE" 'Virtualenv log output'
}
trap handle_exit ERR

# speeds things up when you keep the /env
if [ ! -f /env/bin/activate ]; then
   echo 'Creating virtualenv (this may take a while)'

   python3 -m venv /env

   # shellcheck disable=SC1091
   source /env/bin/activate

   {
      pip3 $PIP_ARGS install setuptools wheel
      pip3 $PIP_ARGS install -r ./requirements.txt
      pip3 $PIP_ARGS install -r ./tests/requirements.txt
      pip3 $PIP_ARGS install -e .
   } &> "$PIP_LOGFILE"
else
   echo 'Using cached virtualenv'

   # shellcheck disable=SC1091
   source /env/bin/activate
fi

# remove the trap
trap - ERR
unset _err
