#!/usr/bin/env bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck source=../globals
source "$DIR"/../globals

# shellcheck source=../python-setup
source "$DIR"/../python-setup

copy_profile

echo ":: Testing Firefox profile writing"

python3 -m pytest -m 'writing and firefox' \
                  --docker \
                  --profile="$PROFILE"
