name: CI
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'tests/**'
      - 'extract_browser_data/**'
      - 'docker-compose.yml'
  schedule:
    # every day at 01:00
    - cron: '0 1 * * *'

jobs:
  firefox-schema-tests:
    runs-on: ubuntu-latest
    name: Firefox Schema Tests
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: |
          sudo docker-compose pull
          sudo docker-compose run test --skip-missing-interpreters=false -e py36 -- -v tests/firefox/test_ff_schema.py
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: firefox-schema-cache
          path: ./.tox
      - run: |
          cat << EOF > ./issue.md
          It seems that Firefox schema has changed
          The run can be found [here](https://github.com/${{ github.repository }}/runs/${{ github.run_id }})
          EOF
        if: failure()
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        if: failure()
        with:
          title: Firefox schema has changed
          content-filepath: ./issue.md
          labels: firefox

  chromium-schema-tests:
    runs-on: ubuntu-latest
    name: Chromium Schema Tests
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: |
          sudo docker-compose pull
          sudo docker-compose run test --skip-missing-interpreters=false -e py36 -- -v tests/chromium/test_ch_schema.py
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: chromium-schema-cache
          path: ./.tox
      - run: |
          cat << EOF > ./issue.md
          It seems that Chromium schema has changed
          The run can be found [here](https://github.com/${{ github.repository }}/runs/${{ github.run_id }})
          EOF
        if: failure()
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        if: failure()
        with:
          title: Chromium schema has changed
          content-filepath: ./issue.md
          labels: chromium

  linux-browser-tests:
    runs-on: ubuntu-latest
    name: Linux ${{ matrix.browser }} (${{ matrix.python }})
    strategy:
      fail-fast: false
      matrix:
        browser: [ 'firefox', 'chromium' ]
        python: [ 'py36' ]
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: |
          sudo docker-compose pull
          sudo docker-compose run test --skip-missing-interpreters=false -e ${{ matrix.python }} -- -m '${{ matrix.browser }}'

  linux-general-tests:
    runs-on: ubuntu-latest
    name: Linux General Tests (${{ matrix.python }})
    strategy:
      fail-fast: false
      matrix:
        python: [ 'py36' ]
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: |
          sudo docker-compose pull
          sudo docker-compose run test --skip-missing-interpreters=false -e ${{ matrix.python }} -- -m 'not browser'

  formatting:
      runs-on: ubuntu-latest
      name: Formatting Checks
      steps:
        - uses: actions/checkout@v2
        - name: Run the test
          run: |
            sudo docker-compose pull
            sudo docker-compose run test --skip-missing-interpreters=false -e format

  mypy:
      runs-on: ubuntu-latest
      name: Type Checks
      steps:
        - uses: actions/checkout@v2
        - name: Run the test
          run: |
            sudo docker-compose pull
            sudo docker-compose run test --skip-missing-interpreters=false -e mypy
