name: CI
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'tests/**'
      - 'extract_browser_data/**'
      - 'docker-compose.yml'

jobs:
  linux-browser-tests:
    runs-on: ubuntu-latest
    name: Linux ${{ matrix.browser }} (${{ matrix.python }})
    strategy:
      fail-fast: false
      matrix:
        browser: [ 'firefox', 'chromium' ]
        python: [ 'py37' ]
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: |
          sudo docker-compose pull
          sudo docker-compose run test -e ${{ matrix.python }} -- -m '${{ matrix.browser }}'

  linux-general-tests:
    runs-on: ubuntu-latest
    name: Linux General Tests (${{ matrix.python }})
    strategy:
      fail-fast: false
      matrix:
        python: [ 'py37' ]
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: |
          sudo docker-compose pull
          sudo docker-compose run test -e ${{ matrix.python }} -- -m 'not browser'

  formatting:
      runs-on: ubuntu-latest
      name: Formatting Checks
      steps:
        - uses: actions/checkout@v2
        - name: Run the test
          run: |
            sudo docker-compose pull
            sudo docker-compose run test -e format

  mypy:
      runs-on: ubuntu-latest
      name: Type Checks
      steps:
        - uses: actions/checkout@v2
        - name: Run the test
          run: |
            sudo docker-compose pull
            sudo docker-compose run test -e mypy
