name: CI
on:
  push:
    branches:
      - ci-testing
    paths:
      - '.github/workflows/ci.yml'
      - 'tests/**'
      - 'extract_browser_data/**'
      - 'docker-compose.yml'
  schedule:
    # every day at 01:00
    - cron: '0 1 * * *'

jobs:
  firefox-schema-tests:
    name: Firefox Schema Tests
    container: quay.io/sandorex/ebd-test-image:ci-testing
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: tox -e py37 -- -v tests/firefox/test_ff_schema.py
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: firefox-cache
          path: ./.tox

  chromium-schema-tests:
    name: Chromium Schema Tests
    container: quay.io/sandorex/ebd-test-image:ci-testing
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: tox -e py37 -- -v tests/chromium/test_ch_schema.py
        env:
          # fixes chromium namespace issue
          CHROMIUM_ARGS: --no-sandbox --disable-gpu
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: chromium-cache
          path: ./.tox

  linux-browser-tests:
    name: Linux ${{ matrix.browser }} (${{ matrix.python }})
    container: quay.io/sandorex/ebd-test-image:ci-testing
    strategy:
      fail-fast: false
      matrix:
        browser: [ 'firefox', 'chromium' ]
        python: [ 'py36', 'py37', 'py38' ]
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: tox -e ${{ matrix.python }} -- -m '${{ matrix.browser }}'

  linux-general-tests:
    name: Linux General Tests (${{ matrix.python }})
    container: quay.io/sandorex/ebd-test-image:ci-testing
    strategy:
      fail-fast: false
      matrix:
        python: [ 'py36', 'py37', 'py38' ]
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: tox -e ${{ matrix.python }} -- -m 'not browser'

  formatting:
    name: Formatting Checks
    container: quay.io/sandorex/ebd-test-image:ci-testing
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: tox -e format

  mypy:
    name: Type Checks
    container: quay.io/sandorex/ebd-test-image:ci-testing
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: tox -e mypy
