name: CI
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - 'tests/**'
      - 'extract_browser_data/**'
      - 'docker-compose.yml'

jobs:
  firefox-schema-tests:
    runs-on: ubuntu-latest
    name: Firefox Schema Tests
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: |
          sudo docker-compose pull
          sudo docker-compose run test --skip-missing-interpreters=false -e py36 -- tests/firefox/test_ff_schema.py
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: firefox-schema-cache-${{ GITHUB_RUN_NUMBER }}
          path: ./.tox

  chromium-schema-tests:
    runs-on: ubuntu-latest
    name: Chromium Schema Tests
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: |
          sudo docker-compose pull
          sudo docker-compose run test --skip-missing-interpreters=false -e py36 -- tests/chromium/test_ch_schema.py
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: chromium-schema-cache-${{ GITHUB_RUN_NUMBER }}
          path: ./.tox

  linux-browser-tests:
    runs-on: ubuntu-latest
    name: Linux ${{ matrix.browser }} (${{ matrix.python }})
    strategy:
      fail-fast: false
      matrix:
        browser: [ 'firefox', 'chromium' ]
        python: [ 'py36' ]
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: |
          sudo docker-compose pull
          sudo docker-compose run test --skip-missing-interpreters=false -e ${{ matrix.python }} -- -m '${{ matrix.browser }}'

  linux-general-tests:
    runs-on: ubuntu-latest
    name: Linux General Tests (${{ matrix.python }})
    strategy:
      fail-fast: false
      matrix:
        python: [ 'py36' ]
    steps:
      - uses: actions/checkout@v2
      - name: Run the test
        run: |
          sudo docker-compose pull
          sudo docker-compose run test --skip-missing-interpreters=false -e ${{ matrix.python }} -- -m 'not browser'

  formatting:
      runs-on: ubuntu-latest
      name: Formatting Checks
      steps:
        - uses: actions/checkout@v2
        - name: Run the test
          run: |
            sudo docker-compose pull
            sudo docker-compose run test --skip-missing-interpreters=false -e format

  mypy:
      runs-on: ubuntu-latest
      name: Type Checks
      steps:
        - uses: actions/checkout@v2
        - name: Run the test
          run: |
            sudo docker-compose pull
            sudo docker-compose run test --skip-missing-interpreters=false -e mypy
